### ISSUE TITLE
Allow minion backend to be configured from the conf file

### ISSUE THREAD

**Issue by mbroadhead** [RexOps/rex-jobcontrol#16]
Currently we are forced to use the `Minion::Backend::File` backend, which is depreciated (see #15). It would be nice if we could provide our own minion backend from the configuration file.

Instead of:
```
{
  minion_db_file => "./minion.data",
}
```

We could do:
```
{
  minion => { SQLite => 'sqlite:test.db' },
}
```
OR:
```
{
  minion => { Pg => 'postgresql://postgres@/test' },
}
```

This would allow users to use any Minion backend that they want, without having to modify the rex-jobcontrol source code.

**Comment by ehuelsmann** [comment]
This has been implemented yesterday on the master branch. Thanks!
