### ISSUE TITLE
Can‘t run ？

### ISSUE THREAD

**Issue by bollwarm** [RexOps/rex-jobcontrol#17]
The mojo and minion have some changes ，and the repo needed update。

**Comment by ehuelsmann** [comment]
@bollwarm I've updated the repo. Does it run for you now?

**Comment by bollwarm** [comment]
NO,there is wrong when run ` cpanm --installdeps .`

-----------------
Configuring /home/lz/test/perl/rex-jobcontrol ... N/A
! Configuring . failed. See /home/lz/.cpanm/work/1563844170.8854/build.log for details.

and the 1563844170.8854/build.log contents : 
================================
cpanm (App::cpanminus) 1.7041 on perl 5.018004 built for x86_64-linux
Work directory is /home/lz/.cpanm/work/1563844170.8854
You have make /usr/bin/make
You have LWP 6.15
You have /bin/tar: tar (GNU tar) 1.23
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
这是自由软件：您可以自由地更改并重新发布它。
在法律所允许的范围内不含任何担保。

由 John Gilmore 和 Jay Fenlason 所写。
You have /usr/bin/unzip
--> Working on .
Entering /home/lz/test/perl/rex-jobcontrol
Configuring /home/lz/test/perl/rex-jobcontrol
-> N/A
! Configuring . failed. See /home/lz/.cpanm/work/1563844170.8854/build.log for details.
Expiring 2 work directories.

**Comment by ehuelsmann** [comment]
Ah. I see. The installation instructions are out-dated / incorrect. I'm working to make sure the tree is in line with the instructions. Thanks for testing!

**Comment by ehuelsmann** [comment]
I merged a fix which addresses the discrepancy between the tree and the README (by fixing the tree). Could you run the same command again and test that it now works? (It does seem to work for me...)

**Comment by bollwarm** [comment]
The installation is OK，ths

The other functions , I will test ...

**Comment by ehuelsmann** [comment]
Ok. Then this specific issue is confirmed closed now. Thanks! Please report further issues as separate issues.
